spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/lmsdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=rootihT22##
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8081

jwt.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
jwt.expiration=86400000

# Email Configuration (Sender.net SMTP)
#spring.mail.host=smtp.sender.net
#spring.mail.port=587
#spring.mail.username=your-sender-email@domain.com
#spring.mail.password=your-sender-api-key
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true


# Brevo SMTP Configuration
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=9abbe3001@smtp-brevo.com
spring.mail.password=xsmtpsib-c21c398501808ada05e0743f28dbeab2adce546ef1c60e85b44ace720f30d2ee-3pnNi2gerkvHyq3O

# TLS and authentication (required)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Your sender email (keep your existing value)
app.sender.email=contact@ontocriptit.com

# Bunny.net Configuration
bunny.stream.library-id=575572
bunny.stream.api-key=af8d231d-71ea-4395-94432291005a-02cd-44aa
bunny.stream.cdn-hostname=vz-9627dfde-1b9.b-cdn.net
bunny.stream.security-key=39deab23-7693-42fc-afaa-2db08a8b33cb
bunny.stream.max-videos-per-month=3

# File Upload Configuration - Increase limits for video files
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB
spring.servlet.multipart.file-size-threshold=10MB

# Connection timeout for large uploads
server.connection-timeout=600000
spring.mvc.async.request-timeout=600000

# WhatsApp Configuration
whatsapp.teacher.number=+94741366365


# Application URL
app.base-url=http://localhost:8081